ModPath = "/mods/TheRedQueen"
Version = "V8"
PersonalityKey = "redqueen"
LogPrefix = "[RedQueen]"

Ticks = {
    IncomeSweep = 100,
    Economy = 10,
    Intel = 20,
    World = 300,
    Strategy = 40,
    Production = 50,
    Combat = 30,
    Team = 100,
    Ping = 20,
}

-- Economy income policy values are expressed in resources per game tick, the
-- unit returned by GetEconomyIncome. Divide a mass-per-second figure by ten.
Policy = {
    ObservationRadius = 48,
    ObserversPerUpdate = 16,
    IntelLifetimeSeconds = 180,
    FreshCombatIntelSeconds = 30,
    ArmyClusterMinimumRadius = 45,
    ArmyClusterMaximumRadius = 90,
    ArmyClusterMapDivisor = 12,
    ArmyApproachDistance = 10,
    ArmyClosingThreatFraction = 0.25,
    PingLifetimeSeconds = 90,
    ExpansionClaimSeconds = 180,
    AttackProposalSeconds = 60,
    ResourceTransferCooldownSeconds = 45,
    ResourceSurplusRatio = 0.85,
    AllyDistressRatio = 0.25,
    ResourceTransferFraction = 0.10,
    OpeningDurationSeconds = 240,
    MinimumProductionMassIncome = 8,
    MinimumAttackUnits = 3,
    MaximumTaskForceUnits = 60,
    AttackReserveFraction = 0.10,
    -- Offensive commitment is tactical, never economic. A wave must carry this
    -- multiple of the observed enemy threat at its destination before it goes.
    CommitmentThreatRatio = 1.10,
    CommitmentThreatRadius = 60,
    CommitmentDiagnosticSeconds = 30,
    UnitOrderLifetimeTicks = 300,
    ObjectiveLifetimeTicks = 300,
    ObjectiveInterruptPriorityGap = 15,
    FactoryCheckCooldownSeconds = 30,
    FactoryCapDiagnosticSeconds = 60,
    MaximumManagedBases = 8,
    FactoryAssistMassPerEngineer = 1.0,
    MaximumFactoryAssistants = 6,
    FactoryAssistSeconds = 30,
    EmergencyDefenseCooldownSeconds = 5,
    EmergencyDefenseEngineerHoldSeconds = 10,
    EmergencyDefenseLogCooldownSeconds = 30,
    EmergencyDefenseRadius = 60,
    EconomyStagnationSeconds = 180,
    EconomyGrowthRatio = 1.05,
    LandLossWindowSeconds = 120,
    LandLossCountThreshold = 8,
    LandLossMassThreshold = 450,
    AirLossWindowSeconds = 120,
    AirLossCountThreshold = 8,
    AirLossMassThreshold = 450,
    GunshipRecoverySeconds = 120,
    CounterDoctrineSeconds = 180,
    GunshipAirThreatRatio = 0.40,
    AirDropTargetRadius = 45,
    AirDropMaximumAirThreat = 6,
    AirDropRequestCooldownSeconds = 90,
    AirDropDiagnosticSeconds = 30,
    MaximumAirDropTransports = 2,
    -- Airdrop allowance plus a ferry reserve. A first calibration against an
    -- observed fleet of 30 that produced no kills; the transport budget
    -- diagnostic reports when it engages so it can be tuned from evidence.
    MaximumTransports = 10,
    Tech2MinimumMassIncome = 4,
    Tech2MinimumEnergyIncome = 60,
    Tech3MinimumMassIncome = 10,
    Tech3MinimumEnergyIncome = 250,
    ExperimentalMinimumMassIncome = 22,
    ExperimentalMinimumEnergyIncome = 800,
    NukeMinimumMassIncome = 30,
    NukeMinimumEnergyIncome = 1200,
    LocalDefenseThreat = 25,
    MassiveArmyThreat = 40,
    MassiveArmyThreatRatio = 1.25,
    CommanderEmergencyThreat = 20,
    CommanderEmergencyThreatRatio = 0.75,
    CommanderEmergencyDistance = 100,
    CommanderAssassinationCriticality = 3.00,
    CommanderAnnihilationCriticality = 2.00,
    CommanderSupremacyCriticality = 1.50,
    MainBaseCriticality = 1.40,
    ExpansionCriticality = 1.00,
    NavalBaseCriticality = 1.00,
    ForwardBaseCriticality = 1.15,
    AnchorProximityTolerance = 16,
    PressureEscalationThreat = 30,
    CombatMomentumWindowSeconds = 120,
    CombatMomentumLossRatio = 1.25,
    CombatMomentumMassDifference = 300,
    DefenseAlertHoldSeconds = 30,
    ForwardBaseMinimumDistance = 80,
    ForwardBaseSiteRadius = 60,
    ForwardBaseSafetyRatio = 0.60,
    ForwardBaseCooldownSeconds = 120,
    ForwardBaseMapKilometersPerBase = 10,
    MaximumForwardBases = 3,
    ForwardBaseMinimumMassIncome = 4,
    ForwardBaseMinimumEnergyIncome = 40,
    ForwardBaseGarrisonSeconds = 60,
    ForwardBaseDiagnosticSeconds = 60,
    ForwardBaseRecordRetentionSeconds = 300,
    -- A remote site must be reached before it can be built. Six minutes retired
    -- bases that were alive and defending; this is the absolute deadline, and a
    -- lost engineer or manager still fails immediately.
    ForwardBaseEstablishSeconds = 900,
    -- A base keeps this many engineers before any may be taken for a forward
    -- base, so sourcing one never strips a base of the engineers it needs.
    ForwardBaseSourceMinimumEngineers = 2,
    StrategicFocusMinimumScore = 35,
    StrategicFocusSwitchMargin = 15,
    StrategicFocusDwellSeconds = 90,
    DefenseAlertEndgameTaxPerSeverity = 0.20,
    DefenseAlertMinimumEndgameRetention = 0.35,
    IncomeSmoothingWeight = 0.25,
    StrategicSecondProjectReadiness = 0.80,
    StrategicSecondProjectArmyMaximum = 70,
    StrategicHighValueThreshold = 80,
    StrategicFortificationThreshold = 40,
}
